# Generated by Django 4.1 on 2023-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_tags_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.CharField(max_length=200),
        ),
    ]
